server:
  port: 8087

spring:
  application:
    name: test
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: root1
      password: root2
      database: mongo
      auto-index-creation: true



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8083/eureka

mongo:
  migration: testing\src\main\resources\migration\MigrationTest.json
